name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: Amadevus/pwsh-script@v2
        id: publish-script
        with:
          script: Publish-Script -Path Register-AzureArtifactRepo.ps1 -NuGetApiKey ${{ secrets.NUGET_API_KEY }}
